# Generated by Django 5.1.5 on 2025-02-26 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0003_alter_movie_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='description',
            field=models.CharField(default='No description available', max_length=250),
            preserve_default=False,
        ),
    ]
